# Data
path: /content/gdrive/My Drive/ComputerVisionPhysiO/PoseDetectionYolov8/data/
#C:/projectstask_physio/data
#/media/veracrypt2/computer_vision/47_pose_detection_yolov8/code/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [7, 3]  # [number of keypoints, number of dim]
flip_idx: [1, 0, 2, 3, 4, 5, 6]

# Classes
names:
  0: body-keypoints
  #human-keypoints